attend: fingerprint
audit: tape
auth: user
bench: list-check
bluetooth: bluetooth
com: grid-round-2-minus
cms: calendar-lines-pen
crm: user-group-simple
datum: table
detail: memo-circle-info
design: pen-ruler
email: envelope
eventual: golf-flag-hole
factory: industry
finance: money-check-dollar
growth: chart-line-up
job: send-backward
markdown: pencil-line
notice: inbox
one_ai: head-side-brain
org: sitemap
print: print
pg: database
roled: user-lock
ship: truck-fast
space: buildings
statis: chart-simple
sync: cloud-arrow-up
trade: cash-register