light:
  - angle-left
  - angle-down
  - angles-right
  - arrow-down
  - arrow-up
  - arrow-up-arrow-down
  - arrows-rotate
  - bars
  - caret-down
  - caret-right
  - cart-shopping
  - certificate
  - check
  - chevron-right
  - circle-info
  - circle-play
  - backward-fast
  - backward-step
  - ellipsis
  - ellipsis-vertical
  - eye
  - filter
  - forward-fast
  - forward-step
  - gears
  - globe
  - grip
  - grid-2
  - house
  - list
  - location-dot
  - magnifying-glass
  - minus
  - pencil
  - plug
  - plus
  - qrcode
  - rotate
  - share
  - sitemap
  - square
  - square-check
  - square-minus
  - star
  - trash
  - trash-can
  - trash-list
  - upload
  - user
  - user-secret
  - users
  - vial
  - xmark
regular:
  - angle-left
  - arrow-down
  - arrow-up
duotone:
  - bluetooth
  - building-user
  - buildings
  - calendar-lines-pen
  - cash-register
  - chart-line-up
  - chart-simple
  - cloud-arrow-up
  - database
  - envelope
  - face-smile
  - fingerprint
  - golf-flag-hole
  - grid-round-2-minus
  - head-side-brain
  - inbox
  - industry
  - list-check
  - memo-circle-info
  - money-check-dollar
  - pen-ruler
  - pencil-line
  - print
  - send-backward
  - sitemap
  - table
  - tape
  - truck-fast
  - user
  - user-group-simple
  - user-lock
