regular:
  - angle-left
  - bars
  - caret-down
  - caret-right
  - cart-shopping
  - certificate
  - check
  - circle-info
  - backward-fast
  - backward-step
  - ellipsis
  - ellipsis-vertical
  - eye
  - forward-fast
  - forward-step
  - gears
  - globe
  - house
  - list
  - location-dot
  - magnifying-glass
  - minus
  - pencil
  - plus
  - qrcode
  - rotate
  - sitemap
  - square
  - square-check
  - square-minus
  - trash
  - upload
  - user
  - user-secret
  - users
  - xmark
light:
  - house
  - list
  - user