regular:
  - angle-left
  - circle-info
  - backward-fast
  - backward-step
  - forward-fast
  - forward-step
  - gears
  - globe
  - pencil
  - plus
  - rotate
  - trash
  - user
  - user-secret
  - xmark