regular:
  - angle-left
  - caret-down
  - caret-right
  - circle-info
  - backward-fast
  - backward-step
  - ellipsis-vertical
  - forward-fast
  - forward-step
  - gears
  - globe
  - house
  - minus
  - pencil
  - plus
  - rotate
  - square
  - square-check
  - square-minus
  - trash
  - user
  - user-secret
  - xmark